### ISSUE TITLE
Repository Manager is not working properly

### ISSUE THREAD

**Issue by vibe13** [project-ncl/pnc#127]
@jdcasey Hi John I noticed this problem when I attempted to launch some builds yesterday and today, when I try to trigger a build, no Jenkins builds are fired. It seems that there is a problem with the initial setup of the Repository Manager:

Caught exception: java.util.concurrent.CompletionException: org.jboss.pnc.core.exception.CoreExceptionWrapper: org.jboss.pnc.spi.repositorymanager.RepositoryManagerException: Failed to setup shared-releases hosted repository: Error retrieving HostedRepository from: admin/hosted. Status was: 400 Bad Request (HTTP/1.1)
at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:205)
at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:482)
at java.util.concurrent.CompletableFuture$Async.run(CompletableFuture.java:428)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.pnc.core.exception.CoreExceptionWrapper: org.jboss.pnc.spi.repositorymanager.RepositoryManagerException: Failed to setup shared-releases hosted repository: Error retrieving HostedRepository from: admin/hosted. Status was: 400 Bad Request (HTTP/1.1)
at org.jboss.pnc.core.builder.BuildCoordinator.lambda$configureRepository$9(BuildCoordinator.java:171)
at org.jboss.pnc.core.builder.BuildCoordinator$$Lambda$19/1391817180.get(Unknown Source)
at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:476)
... 4 more
Caused by: org.jboss.pnc.spi.repositorymanager.RepositoryManagerException: Failed to setup shared-releases hosted repository: Error retrieving HostedRepository from: admin/hosted. Status was: 400 Bad Request (HTTP/1.1)
at org.jboss.pnc.mavenrepositorymanager.RepositoryManagerDriver.createRepository(RepositoryManagerDriver.java:108)
at org.jboss.pnc.mavenrepositorymanager.RepositoryManagerDriver$Proxy$_$$_WeldClientProxy.createRepository(Unknown Source)
at org.jboss.pnc.core.builder.BuildCoordinator.lambda$configureRepository$9(BuildCoordinator.java:169)
... 6 more
Caused by: org.commonjava.aprox.client.core.AproxClientException: Error retrieving HostedRepository from: admin/hosted. Status was: 400 Bad Request (HTTP/1.1)
at org.commonjava.aprox.client.core.AproxClientHttp$3.handleResponse(AproxClientHttp.java:398)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:218)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:136)
at org.commonjava.aprox.client.core.AproxClientHttp.postWithResponse(AproxClientHttp.java:387)
at org.commonjava.aprox.client.core.AproxClientHttp.postWithResponse(AproxClientHttp.java:371)
at org.commonjava.aprox.client.core.module.AproxStoresClientModule.create(AproxStoresClientModule.java:21)
at org.jboss.pnc.mavenrepositorymanager.RepositoryManagerDriver.setupGlobalRepos(RepositoryManagerDriver.java:444)
at org.jboss.pnc.mavenrepositorymanager.RepositoryManagerDriver.createRepository(RepositoryManagerDriver.java:106)
... 8 more

**Comment by jdcasey** [comment]
From what I can tell in the AProx logs, the URL PNC is using seems to be incorrect. It should point to: http://host[:port]/api (where it seems to just be pointing to http://host[:port]/ now).

I've added some code in the maven-repository-manager driver impl to attempt to detect this case and compensate for it, but I think the automated deployment build may be failing due to some missing utility on the server, which is needed for the pnc-web module build...so I'm not sure it'll auto-deploy my solution.

**Comment by vibe13** [comment]
Verified and changed the APROX url, there was a wrong configuration value. Closing this issue, as all works perfectly again.
